global:
  scrape_interval: 5s

scrape_configs:

  - job_name: "job-api"
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: "job-worker"
    static_configs:
      - targets: ["host.docker.internal:4000"]